name: sistempakar
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.3 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  google_fonts: ^4.0.4
  firebase_core: ^2.11.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.5.0
  cloud_firestore: ^4.6.0
  get_storage: ^2.1.1
  fluttertoast: ^8.2.1
  flutter_svg: ^2.0.5
  smart_alert_dialog: ^4.0.4
  flutter_launcher_icons: ^0.13.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter: 
  assets: 
    - assets/images/
    - assets/icons/
  uses-material-design: true

