// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2BtkEy_T_xJJFZF1pWE0JiZYewqebi8k',
    appId: '1:410717750803:web:f6066a87ca1000ddf0e1e6',
    messagingSenderId: '410717750803',
    projectId: 'sistempakar-k7',
    authDomain: 'sistempakar-k7.firebaseapp.com',
    storageBucket: 'sistempakar-k7.appspot.com',
    measurementId: 'G-HV7L9N8LGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKHopGXxuXlbsrcXnB33N4MTiPgLsNUB4',
    appId: '1:410717750803:android:dece2dc6ff23725df0e1e6',
    messagingSenderId: '410717750803',
    projectId: 'sistempakar-k7',
    storageBucket: 'sistempakar-k7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1g7-oZkaOwB9E1RuSWOVjNnyrRpp4Y9I',
    appId: '1:410717750803:ios:626db51933f50a67f0e1e6',
    messagingSenderId: '410717750803',
    projectId: 'sistempakar-k7',
    storageBucket: 'sistempakar-k7.appspot.com',
    iosClientId: '410717750803-sqaj74b84c6ue7ekfkqrat57brc7eklc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistempakar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1g7-oZkaOwB9E1RuSWOVjNnyrRpp4Y9I',
    appId: '1:410717750803:ios:626db51933f50a67f0e1e6',
    messagingSenderId: '410717750803',
    projectId: 'sistempakar-k7',
    storageBucket: 'sistempakar-k7.appspot.com',
    iosClientId: '410717750803-sqaj74b84c6ue7ekfkqrat57brc7eklc.apps.googleusercontent.com',
    iosBundleId: 'com.example.sistempakar',
  );
}
